// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function GetDashboardData() {
  return window['go']['app']['App']['GetDashboardData']();
}

export function GetTask(arg1) {
  return window['go']['app']['App']['GetTask'](arg1);
}

export function GetTasks(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetTasks'](arg1, arg2, arg3, arg4);
}

export function GetTasksByDateFilter(arg1) {
  return window['go']['app']['App']['GetTasksByDateFilter'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['app']['App']['SearchTasks'](arg1);
}

export function ToggleTaskComplete(arg1) {
  return window['go']['app']['App']['ToggleTaskComplete'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}
