// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetDashboardData():Promise<Record<string, any>>;

export function GetTask(arg1:number):Promise<Record<string, any>>;

export function GetTasks(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<Record<string, any>>>;

export function GetTasksByDateFilter(arg1:string):Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function SearchTasks(arg1:string):Promise<Array<Record<string, any>>>;

export function ToggleTaskComplete(arg1:number):Promise<Record<string, any>>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;
